### ISSUE TITLE
Update v1 tag whenever a v1.x version is released

### ISSUE THREAD

**Issue by sethidden** [GitGuardian/ggshield-action#12]
You can see how the official GitHub actions do it: https://github.com/actions/checkout/tags

<img width="1169" alt="image" src="https://github.com/GitGuardian/ggshield-action/assets/5359825/0787c7e9-538f-4d5a-8c73-019df71a38c6">

When v4.1.3 was released, the v4 tag was also updated. This means that people that write "actions/checkout@v4" in their .yml will always use the latest version.

Currently in ggshield action I have written v1.22.0 so each time a new version is released I need to manually update the minor version number. I'd like to just write ggshield-action@v1 and always get the latest minor patch version. Currently @v1.0.0 (which is different than @v1 btw) points to an old version https://github.com/GitGuardian/ggshield-action/releases/tag/v1.0.0

I could just of course write ggshield-action@main but I don't want to be that bleeding edge :P

**Comment by askpatrickw** [comment]
Please do this.

**Comment by agateau-gg** [comment]
Agreed, that makes sense. Going to see how we can fit this in our upcoming sprints.

**Comment by agateau-gg** [comment]
We have a v1 tag now! https://github.com/GitGuardian/ggshield-action/releases/tag/v1
