### ISSUE TITLE
Readme : Requirements section : API Key - Add scope(s)

### ISSUE THREAD

**Issue by hype8912** [GitGuardian/ggshield-action#15]
Will you list the minimum scopes that need to be selected when creating a new personal access token on the GitGuardian website for using this Action with the API?

My initial assumption is `scan` is the only scope but not sure about the rest.

**Comment by agateau-gg** [comment]
Hi, sorry for the late reply. You are correct: only `scan` is required. I am going to rework the README to include this information.
