### ISSUE TITLE
chore: issue new release with Fix for git "dubious ownership" error

### ISSUE THREAD

**Issue by petermetz** [GitGuardian/ggshield-action#6]
Right now the latest release is `v1.1.0` which does not contain the fix for the problem mentioned in the title.
This forces us to specify the version as `"master"` instead of being able to pin it to a specific version (such as `v1.2.0`).
Issuing the release with the mentioned fix would allow us to use a specific version and not have to fall back to a moving target of "master".

**Comment by agateau-gg** [comment]
Thanks for the issue, we just released v1.1.1 to address this.
